import type { FbsEnum, FbsField, FbsSchema, FbsTable, FbsType } from "./model.js";
import { SCALAR_OPS, type ScalarOps } from "./wire.js";

const HEADER = "// Auto-generated by flatbed — do not edit.\n\n";

/** Lookups the emitters share, gathered once from the schema. */
interface Ctx {
  readonly enums: ReadonlyMap<string, FbsEnum>;
}

const ctxOf = (schema: FbsSchema): Ctx => ({
  enums: new Map(schema.enums.map((e) => [e.name, e])),
});

/** The scalar ops backing a scalar/enum wire type (an enum → its underlying). */
const opsFor = (ctx: Ctx, t: FbsType): ScalarOps => {
  if (t.kind === "enum") return SCALAR_OPS[ctx.enums.get(t.name)!.underlying];
  if (t.kind === "scalar") return SCALAR_OPS[t.scalar];
  throw new Error(`no scalar ops for wire kind ${t.kind}`);
};

/** The `n` suffix a scalar/enum literal needs when it is 64-bit backed. */
const suffix = (ctx: Ctx, t: FbsType): string => (opsFor(ctx, t).zero.endsWith("n") ? "n" : "");

/**
 * The wire default a field is compared against (encode's omit-if-equal) and the
 * value it decodes to when absent, as TS literals. The reader already resolved
 * an enum's declared default to its integer value.
 */
const defaults = (ctx: Ctx, f: FbsField): { readonly encode: string; readonly decode: string } => {
  const { type: t, default: d } = f;
  if (t.kind === "scalar" && t.scalar === "bool") {
    const on = d.kind === "int" && d.value !== 0n;
    return { encode: on ? "1" : "0", decode: on ? "true" : "false" };
  }
  if (t.kind === "enum") {
    const lit = `${d.kind === "int" ? d.value : 0n}${suffix(ctx, t)}`;
    return { encode: lit, decode: lit };
  }
  const lit =
    d.kind === "int" ? `${d.value}${suffix(ctx, t)}` : d.kind === "real" ? `${d.value}` : "0";
  return { encode: lit, decode: lit };
};

// -- encode -----------------------------------------------------------------

/** A single-line IIFE building a vector of `element` from `expr`, back-to-front. */
const buildVector = (ctx: Ctx, expr: string, element: FbsType): string => {
  if (element.kind === "table") {
    return `(() => { const o = ${expr}.map((x) => encode${element.name}(builder, x)); builder.startVector(4, o.length, 4); for (let i = o.length - 1; i >= 0; i--) builder.addOffset(o[i]); return builder.endVector(); })()`;
  }
  if (element.kind === "string") {
    return `(() => { const o = ${expr}.map((x) => builder.createString(x)); builder.startVector(4, o.length, 4); for (let i = o.length - 1; i >= 0; i--) builder.addOffset(o[i]); return builder.endVector(); })()`;
  }
  const ops = opsFor(ctx, element);
  const elem = element.kind === "scalar" && element.scalar === "bool" ? "x ? 1 : 0" : "x";
  return `(() => { const a = ${expr}; builder.startVector(${ops.size}, a.length, ${ops.size}); for (let i = a.length - 1; i >= 0; i--) { const x = a[i]; builder.${ops.vecAdd}(${elem}); } return builder.endVector(); })()`;
};

/** `[prep lines, addField line]` for one field's encode. */
const encodeField = (ctx: Ctx, f: FbsField): readonly [string, string] => {
  const val = `value.${f.name}`;
  const off = `${f.name}Offset`;
  const offsetAdd = `  if (${off}) builder.addFieldOffset(${f.id}, ${off}, 0);\n`;
  const t = f.type;
  if (t.kind === "vector") {
    return [`  const ${off} = ${val} != null ? ${buildVector(ctx, val, t.element)} : 0;\n`, offsetAdd];
  }
  if (t.kind === "table") {
    return [`  const ${off} = ${val} != null ? encode${t.name}(builder, ${val}) : 0;\n`, offsetAdd];
  }
  if (t.kind === "string") {
    return [`  const ${off} = ${val} != null ? builder.createString(${val}) : 0;\n`, offsetAdd];
  }
  const ops = opsFor(ctx, t);
  const arg = t.kind === "scalar" && t.scalar === "bool" ? `${val} ? 1 : 0` : val;
  return ["", `  builder.${ops.addField}(${f.id}, ${arg}, ${defaults(ctx, f).encode});\n`];
};

// The vtable needs one slot per field id (not per field): gapped explicit ids
// allocate up to `max id + 1` slots.
const slotCount = (t: FbsTable): number =>
  t.fields.reduce((max, f) => Math.max(max, f.id + 1), 0);

const encodeTable = (ctx: Ctx, t: FbsTable): string => {
  const [preps, adds] = t.fields
    .map((f) => encodeField(ctx, f))
    .reduce<[string, string]>(([p, a], [fp, fa]) => [p + fp, a + fa], ["", ""]);
  return (
    `export function encode${t.name}(builder: flatbuffers.Builder, value: ${t.name}): flatbuffers.Offset {\n` +
    preps +
    `  builder.startObject(${slotCount(t)});\n` +
    adds +
    "  return builder.endObject();\n}\n\n" +
    `export function encode${t.name}Root(value: ${t.name}): Uint8Array {\n` +
    "  const builder = new flatbuffers.Builder();\n" +
    `  builder.finish(encode${t.name}(builder, value));\n` +
    "  return builder.asUint8Array();\n}\n\n"
  );
};

// -- decode -----------------------------------------------------------------

/** The TS expression reading the i-th vector element from `base`. */
const decodeElement = (ctx: Ctx, element: FbsType): string => {
  if (element.kind === "table") return `decode${element.name}(bb, bb.__indirect(base + i * 4))`;
  if (element.kind === "string") return "bb.__string(base + i * 4) as string";
  if (element.kind === "scalar" && element.scalar === "bool") return "bb.readInt8(base + i) !== 0";
  const ops = opsFor(ctx, element);
  const read = `bb.${ops.read}(base + i * ${ops.size})`;
  return element.kind === "enum" ? `${read} as ${element.name}` : read;
};

/** The TS expression reading one field, given `{name}_o` (its vtable offset). */
const decodeField = (ctx: Ctx, f: FbsField): string => {
  const o = `${f.name}_o`;
  const t = f.type;
  if (t.kind === "vector") {
    const tsElem = decodeElementType(t.element);
    return `${o} ? (() => { const len = bb.__vector_len(pos + ${o}); const base = bb.__vector(pos + ${o}); const arr: ${tsElem}[] = []; for (let i = 0; i < len; i++) arr.push(${decodeElement(ctx, t.element)}); return arr; })() : undefined`;
  }
  if (t.kind === "table") return `${o} ? decode${t.name}(bb, bb.__indirect(pos + ${o})) : undefined`;
  if (t.kind === "string") return `${o} ? (bb.__string(pos + ${o}) as string) : undefined`;
  const dec = defaults(ctx, f).decode;
  if (t.kind === "scalar" && t.scalar === "bool") return `${o} ? bb.readInt8(pos + ${o}) !== 0 : ${dec}`;
  const ops = opsFor(ctx, t);
  if (t.kind === "enum") return `(${o} ? bb.${ops.read}(pos + ${o}) : ${dec}) as ${t.name}`;
  return `${o} ? bb.${ops.read}(pos + ${o}) : ${dec}`;
};

/** The TS type of a vector element, for the decoded array's annotation. */
const decodeElementType = (t: FbsType): string => {
  if (t.kind === "table" || t.kind === "enum") return t.name;
  if (t.kind === "string") return "string";
  if (t.kind === "scalar") return SCALAR_OPS[t.scalar].ts;
  return "unknown";
};

const decodeTable = (ctx: Ctx, t: FbsTable): string => {
  const offsets = t.fields
    // Widen before doubling: `id * 2` could overflow a 16-bit id at the top of the range.
    .map((f) => `  const ${f.name}_o = bb.__offset(pos, ${4 + f.id * 2});\n`)
    .join("");
  const fields = t.fields.map((f) => `    ${f.name}: ${decodeField(ctx, f)},\n`).join("");
  return (
    `export function decode${t.name}(bb: flatbuffers.ByteBuffer, pos: number): ${t.name} {\n` +
    offsets +
    "  return {\n" +
    fields +
    "  };\n}\n\n" +
    `export function decode${t.name}Root(bytes: Uint8Array): ${t.name} {\n` +
    "  const bb = new flatbuffers.ByteBuffer(bytes);\n" +
    `  return decode${t.name}(bb, bb.__indirect(bb.position()));\n}\n\n`
  );
};

/** Emit `codec.ts`: per-table encode/decode over the `flatbuffers` runtime. */
export const emitCodec = (schema: FbsSchema): string => {
  const ctx = ctxOf(schema);
  const typeList = [...schema.tables.map((t) => t.name), ...schema.enums.map((e) => e.name)].join(", ");
  return (
    HEADER +
    'import * as flatbuffers from "flatbuffers";\n' +
    `import type { ${typeList} } from "./types.js";\n\n` +
    schema.tables.map((t) => encodeTable(ctx, t) + decodeTable(ctx, t)).join("")
  );
};
