import type { Operation } from "./model.js";
import {
  camelCase,
  isReservedMethodName,
  isValidTsIdentifier,
  paramIdent,
  pascalCase,
  pathParams,
} from "./identifiers.js";

const HEADER = "// Auto-generated by flatbed — do not edit.\n\n";

/** GET/HEAD never carry a body, so their request type is dropped. */
const effectiveRequestType = (op: Operation): string | undefined =>
  op.method === "GET" || op.method === "HEAD" ? undefined : op.requestType;

/** The camelCased operationId when present, else `<method><PascalPathSegments>`. */
export const methodName = (op: Operation): string => {
  if (op.operationId !== undefined) return camelCase(op.operationId);
  const segments = op.path.split("/").filter((s) => s.length > 0);
  const word = (seg: string): string =>
    seg.startsWith("{") && seg.endsWith("}") ? `By${pascalCase(seg.slice(1, -1))}` : pascalCase(seg);
  return op.method.toLowerCase() + segments.map(word).join("");
};

/** Throw if any operation derives a method or argument name that won't compile. */
export const checkNames = (ops: readonly Operation[]): void => {
  const seen = new Map<string, string>();
  ops.forEach((op) => {
    const name = methodName(op);
    const sig = `${op.method} ${op.path}`;
    if (!isValidTsIdentifier(name)) {
      throw new Error(
        `operation \`${sig}\` derives the client method name \`${name}\`, which is not a valid TypeScript identifier — set an explicit operationId`,
      );
    }
    if (isReservedMethodName(name)) {
      throw new Error(
        `operation \`${sig}\` derives the client method name \`${name}\`, which collides with a member the base client already defines — set a different operationId`,
      );
    }
    const prev = seen.get(name);
    if (prev !== undefined) {
      throw new Error(
        `two operations derive the same client method \`${name}\`: \`${prev}\` and \`${sig}\` — give one an explicit operationId to disambiguate`,
      );
    }
    seen.set(name, sig);

    const hasBody = effectiveRequestType(op) !== undefined;
    const paramIdents = new Set<string>();
    pathParams(op.path).forEach((param) => {
      const ident = paramIdent(param);
      if (hasBody && ident === "body") {
        throw new Error(
          `operation \`${sig}\` has a path parameter \`${param}\` that maps to the argument name \`body\`, the request-body argument — rename it in the spec`,
        );
      }
      if (paramIdents.has(ident)) {
        throw new Error(
          `operation \`${sig}\` has two path parameters that map to the argument name \`${ident}\` — rename one in the spec`,
        );
      }
      paramIdents.add(ident);
    });
  });
};

const pathExpr = (op: Operation, params: readonly string[]): string =>
  params.length === 0
    ? `"${op.path}"`
    : "`" +
      params.reduce(
        // Encode each value: a `/`, `?`, `#`, `&`, or space would otherwise
        // reshape or misroute the request URL.
        (tmpl, p) => tmpl.replace(`{${p}}`, `\${encodeURIComponent(${paramIdent(p)})}`),
        op.path,
      ) +
      "`";

const method = (op: Operation): string => {
  const params = pathParams(op.path);
  const req = effectiveRequestType(op);
  const args = [
    ...params.map((p) => `${paramIdent(p)}: string`),
    ...(req !== undefined ? [`body: ${req}`] : []),
  ].join(", ");
  const returns = op.responseType ?? "Uint8Array";
  const body = req !== undefined ? `codec.encode${req}Root(body)` : "new Uint8Array()";
  const decode =
    op.responseType !== undefined ? `codec.decode${op.responseType}Root` : "(bytes: Uint8Array) => bytes";
  return (
    `  ${methodName(op)}(${args}): Promise<${returns}> {\n` +
    `    return this.request("${op.method}", ${pathExpr(op, params)}, ${body}, ${decode});\n` +
    "  }\n\n"
  );
};

/**
 * Emit `client.ts`: one method per operation, extending the package's
 * `FlatbedClient`. Assumes {@link checkNames} has passed — names are emitted
 * verbatim.
 */
export const emitClient = (ops: readonly Operation[]): string => {
  const importTypes = [
    ...new Set(
      ops.flatMap((op) => [effectiveRequestType(op), op.responseType].filter((t) => t !== undefined)),
    ),
  ].sort();
  const usesCodec = ops.some((op) => effectiveRequestType(op) !== undefined || op.responseType !== undefined);
  return (
    HEADER +
    'import { FlatbedClient as FlatbedClientBase } from "@plonklabs/flatbed-client";\n' +
    (usesCodec ? 'import * as codec from "./codec.js";\n' : "") +
    (importTypes.length > 0 ? `import type { ${importTypes.join(", ")} } from "./types.js";\n` : "") +
    "\nexport class FlatbedClient extends FlatbedClientBase {\n" +
    ops.map(method).join("") +
    "}\n"
  );
};

/** Emit the `index.ts` barrel re-exporting the generated folder. */
export const emitIndex = (): string =>
  HEADER +
  'export * from "./types.js";\n' +
  'export * from "./client.js";\n' +
  'export * as codec from "./codec.js";\n';
