//! Emit the high-level `<stem>_flatbed.rs` from reflection-derived
//! `Table`/`Enum` shadow types.
//!
//! Each namespace becomes its own `pub mod` containing:
//! - re-exports of flatc-generated enum types from the hidden `__fb` submodule
//! - per-enum serde adapter modules that round-trip JSON as variant-name strings
//! - plain Rust structs with serde + utoipa derives
//! - inherent `to_flatbuffer` / `from_flatbuffer` helpers
//! - `flatbed::ToFlatBuffer` / `HasJsonCompanion` / `HasPlainStruct` impls

use crate::fbs_types::{
    fbs_type_to_openapi, fbs_type_to_rust_type, is_enum_type, is_enum_vector, is_optional_type,
    is_table_type, is_table_vector, is_vector_type, vector_inner_type,
};
use crate::reflection::{Enum, EnumsByNamespace, Table, TablesByNamespace};

/// Generate all-in-one flatbed module content with plain Rust structs as primary API
///
/// The generated content is meant to be wrapped by the user in their own module:
/// ```rust,ignore
/// mod generated {
///     include!(concat!(env!("OUT_DIR"), "/agent_flatbed.rs"));
/// }
/// ```
///
/// Access types as plain structs:
/// - `generated::v_1::PingRequest` (plain struct - primary API)
/// - `generated::v_1::PingResponse` (plain struct - primary API)
///
/// FlatBuffer internals are hidden in the `__fb` submodule.
pub(crate) fn generate_flatbed_module(
    schemas_by_namespace: &TablesByNamespace,
    enums_by_namespace: &EnumsByNamespace,
    stem: &str,
) -> String {
    let mut output = String::new();

    // Header
    output.push_str("// Auto-generated by flatbed_build - do not edit\n\n");

    // Include FlatBuffer generated code in a private module (internals hidden)
    output.push_str("#[doc(hidden)]\n");
    output.push_str("pub mod __fb {\n");
    output.push_str(&format!("    include!(\"{}_generated.rs\");\n", stem));
    output.push_str("}\n\n");

    // Union the namespace key set so a namespace containing only enums (no
    // tables) still gets a `pub mod` with its enum re-exports.
    let mut namespaces: std::collections::BTreeSet<&String> = std::collections::BTreeSet::new();
    namespaces.extend(schemas_by_namespace.keys());
    namespaces.extend(enums_by_namespace.keys());

    // Generate plain struct modules (primary API)
    for namespace in namespaces {
        let empty_tables: Vec<Table> = Vec::new();
        let empty_enums: Vec<Enum> = Vec::new();
        let tables = schemas_by_namespace.get(namespace).unwrap_or(&empty_tables);
        let enums = enums_by_namespace.get(namespace).unwrap_or(&empty_enums);
        generate_plain_struct_module(&mut output, namespace, tables, enums);
    }

    output
}

/// Generate plain struct module for a namespace (primary API)
fn generate_plain_struct_module(
    output: &mut String,
    namespace: &str,
    tables: &[Table],
    enums: &[Enum],
) {
    let table_names: Vec<String> = tables.iter().map(|t| t.name.clone()).collect();
    let enum_names: Vec<String> = enums.iter().map(|e| e.name.clone()).collect();

    // Per-enum serde adapter modules use a lowercased name (`_severity_serde`,
    // `_severity_opt_vec_serde`). Two enums in the same namespace whose names
    // only differ by case (`BoxProtocol` vs `boxprotocol`) would emit
    // duplicate `mod` blocks and produce a confusing rustc error far from
    // the .fbs file. Fail loud at codegen time instead.
    {
        let mut seen: std::collections::HashMap<String, &str> = std::collections::HashMap::new();
        for name in &enum_names {
            let lower = name.to_lowercase();
            if let Some(prev) = seen.insert(lower.clone(), name.as_str()) {
                panic!(
                    "enum names '{prev}' and '{name}' collide on lowercased serde adapter module '_{lower}_serde' in namespace '{namespace}'. Rename one of them."
                );
            }
        }
    }

    output.push_str(&format!("pub mod {} {{\n", namespace));
    output.push_str("    use ::flatbed::serde::{Deserialize, Serialize};\n");
    output.push_str("    use ::flatbed::flatbuffers::FlatBufferBuilder;\n");
    output.push_str("    // Import utoipa as module name so ToSchema derive macro finds it\n");
    output.push_str("    use ::flatbed::utoipa;\n");
    output.push_str("    use utoipa::ToSchema;\n\n");

    // Re-export each enum from the flatc-generated `__fb` module so callers
    // can name the type as `generated::v_1::Severity::Info` without crossing
    // the `__fb` boundary. The flatc enum already implements every trait we
    // need for FlatBuffer round-trips (`Default`, `Copy`, `EndianScalar`,
    // `Push`, `Follow`), so a plain `pub use` is enough.
    for enum_name in &enum_names {
        output.push_str(&format!(
            "    pub use super::__fb::{}::{};\n",
            namespace, enum_name
        ));
    }
    if !enum_names.is_empty() {
        output.push('\n');
    }

    // Per-enum serde adapter modules. flatc emits `pub struct Severity(pub <T>)`
    // without `Serialize` / `Deserialize` derives, and the orphan rule blocks
    // us from adding our own impls (the type lives in `__fb`, the traits in
    // `serde`). The adapters round-trip JSON as variant-name strings —
    // `{"severity": "Error"}` — so the wire form matches the
    // `#[schema(value_type = String)]` override on the field. Any client
    // generated from the OpenAPI spec sees the same shape it deserialises.
    // The FlatBuffer wire format is unaffected: bare-enum and `[Enum]`
    // fields still take the scalar / scalar-vector codegen path and
    // serialise as the underlying integer at the FB layer.
    for enum_def in enums {
        let name = &enum_def.name;
        let lower = name.to_lowercase();
        let variants = &enum_def.variants;

        let valid_names_csv = variants
            .iter()
            .map(|v| format!("\"{v}\""))
            .collect::<Vec<_>>()
            .join(", ");

        let mut variant_to_name = String::new();
        for (i, variant) in variants.iter().enumerate() {
            let prefix = if i == 0 { "if" } else { "else if" };
            variant_to_name.push_str(&format!(
                "                {prefix} *v == {name}::{variant} {{ \"{variant}\" }}\n"
            ));
        }
        if variants.is_empty() {
            // No variants declared — emit a stub that always errors at runtime
            // on serialise. This shouldn't happen for valid .fbs schemas, but
            // keeps the codegen total without panicking the build.
            variant_to_name.push_str("                { return Err(<S::Error as ::flatbed::serde::ser::Error>::custom(\"empty enum\")); }\n");
        } else {
            variant_to_name.push_str(&format!(
                "                else {{ return Err(<S::Error as ::flatbed::serde::ser::Error>::custom(format!(\"unknown {name} variant: {{:?}}\", v.0))); }}\n"
            ));
        }

        let mut name_to_variant_arms = String::new();
        for variant in variants {
            name_to_variant_arms.push_str(&format!(
                "                \"{variant}\" => Ok({name}::{variant}),\n"
            ));
        }

        // Single-value adapter (used for bare-enum fields).
        output.push_str(&format!(
            concat!(
                "    #[doc(hidden)]\n",
                "    pub mod _{lower}_serde {{\n",
                "        use super::{name};\n",
                "        use ::flatbed::serde::{{Deserialize, Deserializer, Serialize, Serializer}};\n",
                "        const VALID_NAMES: &[&str] = &[{valid_names_csv}];\n",
                "        pub fn serialize<S: Serializer>(v: &{name}, s: S) -> Result<S::Ok, S::Error> {{\n",
                "            let name: &'static str = {{\n",
                "{variant_to_name}",
                "            }};\n",
                "            name.serialize(s)\n",
                "        }}\n",
                "        pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<{name}, D::Error> {{\n",
                "            let raw = String::deserialize(d)?;\n",
                "            match raw.as_str() {{\n",
                "{name_to_variant_arms}",
                "                other => Err(<D::Error as ::flatbed::serde::de::Error>::unknown_variant(other, VALID_NAMES)),\n",
                "            }}\n",
                "        }}\n",
                "    }}\n",
            ),
            lower = lower,
            name = name,
            valid_names_csv = valid_names_csv,
            variant_to_name = variant_to_name,
            name_to_variant_arms = name_to_variant_arms,
        ));

        // Optional<Vec<Enum>> adapter (used for `[Enum]` fields, which surface
        // as `Option<Vec<EnumName>>` in the Rust struct). Serialises as
        // `["Info", "Warning", ...]`; deserialises the same shape back.
        output.push_str(&format!(
            concat!(
                "    #[doc(hidden)]\n",
                "    pub mod _{lower}_opt_vec_serde {{\n",
                "        use super::{name};\n",
                "        use ::flatbed::serde::{{Deserialize, Deserializer, Serialize, Serializer}};\n",
                "        const VALID_NAMES: &[&str] = &[{valid_names_csv}];\n",
                "        fn variant_to_name<S: Serializer>(v: &{name}) -> Result<&'static str, S::Error> {{\n",
                "            let name: &'static str = {{\n",
                "{variant_to_name}",
                "            }};\n",
                "            Ok(name)\n",
                "        }}\n",
                "        pub fn serialize<S: Serializer>(v: &Option<Vec<{name}>>, s: S) -> Result<S::Ok, S::Error> {{\n",
                "            match v {{\n",
                "                Some(items) => {{\n",
                "                    let names: Result<Vec<&'static str>, S::Error> = items.iter().map(variant_to_name::<S>).collect();\n",
                "                    Some(names?).serialize(s)\n",
                "                }}\n",
                "                None => Option::<Vec<&'static str>>::None.serialize(s),\n",
                "            }}\n",
                "        }}\n",
                "        pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Option<Vec<{name}>>, D::Error> {{\n",
                "            let raw: Option<Vec<String>> = Option::deserialize(d)?;\n",
                "            match raw {{\n",
                "                Some(names) => {{\n",
                "                    let parsed: Result<Vec<{name}>, D::Error> = names.into_iter().map(|raw| match raw.as_str() {{\n",
                "{name_to_variant_arms}",
                "                        other => Err(<D::Error as ::flatbed::serde::de::Error>::unknown_variant(other, VALID_NAMES)),\n",
                "                    }}).collect();\n",
                "                    parsed.map(Some)\n",
                "                }}\n",
                "                None => Ok(None),\n",
                "            }}\n",
                "        }}\n",
                "    }}\n",
            ),
            lower = lower,
            name = name,
            valid_names_csv = valid_names_csv,
            variant_to_name = variant_to_name,
            name_to_variant_arms = name_to_variant_arms,
        ));
    }
    if !enum_names.is_empty() {
        output.push('\n');
    }

    // Generate all plain structs first (forward declarations for nested references)
    for table in tables {
        generate_plain_struct(output, table, &table_names, &enum_names);
    }

    // Generate impl blocks with to_flatbuffer and from_flatbuffer methods
    for table in tables {
        generate_plain_struct_impl(output, table, namespace, &table_names);
        generate_default_impl(output, table);
        generate_flatbed_trait_impls(output, table, namespace, &table_names);
    }

    output.push_str("}\n"); // close namespace module
}

/// Generate plain struct definition (4 spaces indent, inside namespace module).
///
/// `Default` is dropped from the derive list when any field carries an
/// FB-declared non-zero default; a hand-written `impl Default` is emitted
/// separately (`generate_default_impl`) so each field gets its declared
/// value instead of the field type's zero. Tables with no non-zero
/// defaults keep `#[derive(Default)]` so their generated snapshots stay
/// byte-identical with what shipped before defaults were supported.
fn generate_plain_struct(
    output: &mut String,
    table: &Table,
    table_names: &[String],
    enum_names: &[String],
) {
    let has_custom_default = table.fields.iter().any(|f| f.default.is_some());
    let derives = if has_custom_default {
        "Serialize, Deserialize, Clone, Debug, PartialEq, ToSchema"
    } else {
        "Serialize, Deserialize, Clone, Debug, Default, PartialEq, ToSchema"
    };
    output.push_str(&format!("    #[derive({})]\n", derives));
    output.push_str("    #[serde(crate = \"::flatbed::serde\")]\n");
    output.push_str(&format!("    pub struct {} {{\n", table.name));

    for field in &table.fields {
        let rust_type = fbs_type_to_rust_type(&field.fbs_type, table_names, enum_names);

        // Enum fields need:
        // 1. A `value_type` override on `ToSchema`. flatc emits enums as
        //    `pub struct Severity(pub i8)` without any `utoipa` derives, so
        //    plain forwarding would fail with "ComposeSchema not implemented".
        //    The override declares the JSON form is a String — which matches
        //    the serde adapter below.
        // 2. A `serde(with = ...)` adapter that round-trips JSON as a
        //    variant-name string ("Info", "Warning", …). The flatc enum
        //    doesn't derive Serialize/Deserialize and the orphan rule
        //    blocks us from adding the impls ourselves.
        if is_enum_type(&field.fbs_type, enum_names) {
            // `default` matches FlatBuffers' "absent scalar = zero variant"
            // wire semantics; without it, JSON callers that omit the key
            // would hit a hard deserialisation error instead of getting the
            // first variant (which the flatc enum already derives Default for).
            output.push_str("        #[schema(value_type = String)]\n");
            output.push_str(&format!(
                "        #[serde(with = \"_{}_serde\", default)]\n",
                field.fbs_type.to_lowercase()
            ));
        } else if is_enum_vector(&field.fbs_type, enum_names) {
            let inner = vector_inner_type(&field.fbs_type);
            output.push_str("        #[schema(value_type = Vec<String>)]\n");
            output.push_str(&format!(
                "        #[serde(with = \"_{}_opt_vec_serde\", default)]\n",
                inner.to_lowercase()
            ));
        }

        output.push_str(&format!("        pub {}: {},\n", field.name, rust_type));
    }

    output.push_str("    }\n\n");
}

/// Generate plain struct impl block with to_flatbuffer and from_flatbuffer methods.
///
/// FlatBuffer enums share the wire-format with primitives: they implement
/// `Push + Copy` and decode as `Self` via `Follow`. So:
/// - a single enum field takes the scalar path (`{name}: self.{name}`,
///   `{name}: fb.{name}()`)
/// - an `[Enum]` vector field takes the scalar-vector path
///   (`builder.create_vector(v)`, `v.iter().collect()`)
///
/// The encoder/decoder branches don't need to distinguish enum-typed
/// fields explicitly, so this function takes no `enum_names` parameter.
fn generate_plain_struct_impl(
    output: &mut String,
    table: &Table,
    namespace: &str,
    table_names: &[String],
) {
    output.push_str(&format!("    impl {} {{\n", table.name));

    // to_flatbuffer method
    output.push_str("        /// Convert this struct to FlatBuffer binary format\n");
    output.push_str("        pub fn to_flatbuffer(&self) -> Vec<u8> {\n");
    output.push_str("            let mut builder = FlatBufferBuilder::new();\n");
    output.push_str("            let root = self.build_flatbuffer(&mut builder);\n");
    output.push_str("            builder.finish(root, None);\n");
    output.push_str("            builder.finished_data().to_vec()\n");
    output.push_str("        }\n\n");

    // from_flatbuffer method
    output.push_str("        /// Parse from FlatBuffer binary format\n");
    output.push_str("        pub fn from_flatbuffer(bytes: &[u8]) -> Result<Self, ::flatbed::flatbuffers::InvalidFlatbuffer> {\n");
    output.push_str(&format!(
        "            let fb = ::flatbed::flatbuffers::root::<super::__fb::{}::{}>(&bytes)?;\n",
        namespace, table.name
    ));
    output.push_str("            Ok(Self::from_fb(&fb))\n");
    output.push_str("        }\n\n");

    // Internal helper to build into an existing builder (for nested tables)
    output.push_str("        #[doc(hidden)]\n");
    output.push_str(&format!(
        "        pub fn build_flatbuffer<'a>(&self, builder: &mut FlatBufferBuilder<'a>) -> ::flatbed::flatbuffers::WIPOffset<super::__fb::{}::{}<'a>> {{\n",
        namespace, table.name
    ));

    // Create strings and nested tables first
    for field in &table.fields {
        if field.fbs_type == "string" {
            output.push_str(&format!(
                "            let {}_offset = self.{}.as_ref().map(|s| builder.create_string(s));\n",
                field.name, field.name
            ));
        } else if is_vector_type(&field.fbs_type) {
            let inner = vector_inner_type(&field.fbs_type);
            if inner == "string" {
                output.push_str(&format!(
                    concat!(
                        "            let {0}_offset = self.{0}.as_ref().map(|v| {{\n",
                        "                let offsets: Vec<_> = v.iter().map(|s| builder.create_string(s.as_str())).collect();\n",
                        "                builder.create_vector(&offsets)\n",
                        "            }});\n",
                    ),
                    field.name
                ));
            } else if is_table_vector(&field.fbs_type, table_names) {
                // Table vector — recursively build each element, then write the
                // resulting WIPOffsets as a single vector.
                output.push_str(&format!(
                    concat!(
                        "            let {0}_offset = self.{0}.as_ref().map(|v| {{\n",
                        "                let offsets: Vec<_> = v.iter().map(|t| t.build_flatbuffer(builder)).collect();\n",
                        "                builder.create_vector(&offsets)\n",
                        "            }});\n",
                    ),
                    field.name
                ));
            } else {
                // Scalar vector — FlatBuffers accepts a slice of primitives
                // directly. This branch also covers `[Enum]`: flatc-generated
                // enum types implement `Push + Copy`, so `create_vector(&[T])`
                // works without any per-element conversion.
                output.push_str(&format!(
                    "            let {0}_offset = self.{0}.as_ref().map(|v| builder.create_vector(v));\n",
                    field.name
                ));
            }
        } else if is_table_type(&field.fbs_type, table_names) {
            output.push_str(&format!(
                "            let {}_offset = self.{}.as_ref().map(|t| t.build_flatbuffer(builder));\n",
                field.name, field.name
            ));
        }
    }

    // Create the table
    output.push_str(&format!(
        "            super::__fb::{}::{}::create(builder, &super::__fb::{}::{}Args {{\n",
        namespace, table.name, namespace, table.name
    ));

    for field in &table.fields {
        if field.fbs_type == "string"
            || is_table_type(&field.fbs_type, table_names)
            || is_vector_type(&field.fbs_type)
        {
            output.push_str(&format!(
                "                {}: {}_offset,\n",
                field.name, field.name
            ));
        } else {
            // Scalar (primitive or enum) — emit directly. Enums are `Copy`
            // and live in the same category as primitives at the wire level,
            // so no `.clone()` is needed.
            output.push_str(&format!(
                "                {}: self.{},\n",
                field.name, field.name
            ));
        }
    }

    output.push_str("            })\n");
    output.push_str("        }\n\n");

    // Internal helper to convert from FlatBuffer view type
    output.push_str("        #[doc(hidden)]\n");
    output.push_str(&format!(
        "        pub fn from_fb(fb: &super::__fb::{}::{}) -> Self {{\n",
        namespace, table.name
    ));
    output.push_str("            Self {\n");

    for field in &table.fields {
        if field.fbs_type == "string" {
            output.push_str(&format!(
                "                {}: fb.{}().map(|s| s.to_string()),\n",
                field.name, field.name
            ));
        } else if is_vector_type(&field.fbs_type) {
            let inner = vector_inner_type(&field.fbs_type);
            if inner == "string" {
                output.push_str(&format!(
                    "                {}: fb.{}().map(|v| v.iter().map(|s| s.to_string()).collect()),\n",
                    field.name, field.name
                ));
            } else if is_table_vector(&field.fbs_type, table_names) {
                // Table vector — iterate the FlatBuffer view, convert each
                // element via the corresponding `from_fb` helper.
                output.push_str(&format!(
                    "                {}: fb.{}().map(|v| v.iter().map(|t| {}::from_fb(&t)).collect()),\n",
                    field.name, field.name, inner
                ));
            } else {
                // Scalar vector — iterate and collect into Vec<T>
                output.push_str(&format!(
                    "                {}: fb.{}().map(|v| v.iter().collect()),\n",
                    field.name, field.name
                ));
            }
        } else if is_table_type(&field.fbs_type, table_names) {
            output.push_str(&format!(
                "                {}: fb.{}().map(|t| {}::from_fb(&t)),\n",
                field.name, field.name, field.fbs_type
            ));
        } else {
            output.push_str(&format!(
                "                {}: fb.{}(),\n",
                field.name, field.name
            ));
        }
    }

    output.push_str("            }\n");
    output.push_str("        }\n");

    output.push_str("    }\n\n");
}

/// Emit a hand-written `impl Default` for tables whose FB schema declares
/// any non-zero field default. Fields without an override fall back to
/// `Default::default()` of their field type, matching what `derive(Default)`
/// would have produced — so adding one defaulted field doesn't perturb the
/// behavior of the others.
///
/// Tables with no non-zero defaults skip this emission entirely; their
/// struct keeps `#[derive(Default)]` from `generate_plain_struct` and the
/// generated `_flatbed.rs` stays byte-identical with the pre-defaults shape.
fn generate_default_impl(output: &mut String, table: &Table) {
    if !table.fields.iter().any(|f| f.default.is_some()) {
        return;
    }
    output.push_str(&format!("    impl Default for {} {{\n", table.name));
    output.push_str("        fn default() -> Self {\n");
    output.push_str("            Self {\n");
    for field in &table.fields {
        let expr = field.default.as_deref().unwrap_or("Default::default()");
        output.push_str(&format!("                {}: {},\n", field.name, expr));
    }
    output.push_str("            }\n");
    output.push_str("        }\n");
    output.push_str("    }\n\n");
}

/// Generate flatbed trait implementations for the plain struct
fn generate_flatbed_trait_impls(
    output: &mut String,
    table: &Table,
    namespace: &str,
    table_names: &[String],
) {
    // ToFlatBuffer trait implementation
    output.push_str(&format!(
        "    impl ::flatbed::ToFlatBuffer for {} {{\n",
        table.name
    ));

    // SCHEMA_FIELDS associated const
    output.push_str("        const SCHEMA_FIELDS: &'static [::flatbed::FieldInfo] = &[\n");
    for field in &table.fields {
        let openapi_type = if is_table_type(&field.fbs_type, table_names) {
            "object"
        } else {
            fbs_type_to_openapi(&field.fbs_type)
        };
        let required =
            !is_optional_type(&field.fbs_type) && !is_table_type(&field.fbs_type, table_names);
        output.push_str(&format!(
            "            ::flatbed::FieldInfo {{ name: \"{}\", field_type: \"{}\", fbs_type: \"{}\", required: {} }},\n",
            field.name, openapi_type, field.fbs_type, required
        ));
    }
    output.push_str("        ];\n\n");

    // SCHEMA_NAME associated const
    output.push_str(&format!(
        "        const SCHEMA_NAME: &'static str = \"{}\";\n\n",
        table.name
    ));

    // to_flatbuffer method (delegates to inherent impl)
    output.push_str("        fn to_flatbuffer(&self) -> Vec<u8> {\n");
    output.push_str("            self.to_flatbuffer()\n");
    output.push_str("        }\n");
    output.push_str("    }\n\n");

    // HasJsonCompanion trait implementation (plain struct IS the companion now)
    output.push_str(&format!(
        "    impl ::flatbed::HasJsonCompanion for super::__fb::{}::{}<'_> {{\n",
        namespace, table.name
    ));
    output.push_str(&format!("        type Json = {};\n", table.name));
    output.push_str("    }\n\n");

    // Also implement HasJsonCompanion for the plain struct itself (self-referential)
    output.push_str(&format!(
        "    impl ::flatbed::HasPlainStruct for {} {{\n",
        table.name
    ));
    output.push_str(&format!("        type Plain = {};\n", table.name));
    output.push_str(&format!(
        "        type FlatBuffer<'a> = super::__fb::{}::{}<'a>;\n",
        namespace, table.name
    ));
    output.push_str("    }\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reflection::{Enum, Field, Table};
    use std::collections::HashMap;

    #[test]
    fn test_generate_flatbed_module_versioned() {
        let mut schemas: HashMap<String, Vec<Table>> = HashMap::new();
        schemas.insert(
            "v_1".to_string(),
            vec![Table {
                name: "TestType".to_string(),
                fields: vec![Field {
                    name: "value".to_string(),
                    fbs_type: "string".to_string(),
                    default: None,
                }],
            }],
        );
        let enums: HashMap<String, Vec<Enum>> = HashMap::new();

        let module = generate_flatbed_module(&schemas, &enums, "test");

        // Check header
        assert!(module.contains("// Auto-generated by flatbed_build - do not edit"));

        // Check FlatBuffer internals are hidden in __fb module
        assert!(module.contains("pub mod __fb {"));
        assert!(module.contains("include!(\"test_generated.rs\");"));

        // Check plain struct module
        assert!(module.contains("pub mod v_1 {"));

        // Check plain struct (no Json suffix)
        assert!(module.contains("pub struct TestType {"));
        assert!(module.contains("impl ::flatbed::ToFlatBuffer for TestType"));
        assert!(
            module.contains("impl ::flatbed::HasJsonCompanion for super::__fb::v_1::TestType<'_>")
        );
    }

    #[test]
    fn test_generate_flatbed_module_with_table_vector() {
        let mut schemas = HashMap::new();
        schemas.insert(
            "v_1".to_string(),
            vec![
                Table {
                    name: "Address".to_string(),
                    fields: vec![Field {
                        name: "city".to_string(),
                        fbs_type: "string".to_string(),
                        default: None,
                    }],
                },
                Table {
                    name: "AddressBook".to_string(),
                    fields: vec![Field {
                        name: "entries".to_string(),
                        fbs_type: "[Address]".to_string(),
                        default: None,
                    }],
                },
            ],
        );
        let enums: HashMap<String, Vec<Enum>> = HashMap::new();
        let module = generate_flatbed_module(&schemas, &enums, "test");

        // Struct field type
        assert!(module.contains("pub entries: Option<Vec<Address>>"));
        // Builder: each element recursively built, then create_vector over the offsets
        assert!(module.contains("|t| t.build_flatbuffer(builder)"));
        // Decoder: iterate FlatBuffer view, convert via the inner table's from_fb
        assert!(module.contains("|t| Address::from_fb(&t)"));
    }

    #[test]
    fn test_generate_flatbed_module_with_scalar_vector() {
        let mut schemas = HashMap::new();
        schemas.insert(
            "v_1".to_string(),
            vec![Table {
                name: "Stats".to_string(),
                fields: vec![Field {
                    name: "values".to_string(),
                    fbs_type: "[int32]".to_string(),
                    default: None,
                }],
            }],
        );
        let enums: HashMap<String, Vec<Enum>> = HashMap::new();
        let module = generate_flatbed_module(&schemas, &enums, "test");
        assert!(module.contains("pub values: Option<Vec<i32>>"));
        assert!(module.contains("builder.create_vector(v)"));
        assert!(module.contains("v.iter().collect()"));
    }

    #[test]
    fn test_generate_flatbed_module_with_vector() {
        let mut schemas = HashMap::new();
        schemas.insert(
            "v_1".to_string(),
            vec![Table {
                name: "RegistryEndpoints".to_string(),
                fields: vec![Field {
                    name: "endpoints".to_string(),
                    fbs_type: "[string]".to_string(),
                    default: None,
                }],
            }],
        );
        let enums: HashMap<String, Vec<Enum>> = HashMap::new();
        let module = generate_flatbed_module(&schemas, &enums, "test");
        assert!(module.contains("pub endpoints: Option<Vec<String>>"));
        assert!(module.contains("create_vector"));
        assert!(module.contains("v.iter().map(|s| s.to_string()).collect()"));
    }

    #[test]
    #[should_panic(expected = "collide on lowercased serde adapter module")]
    fn test_generate_flatbed_module_panics_on_lowercase_collision() {
        // Two enum names that differ only in case lowercase to the same
        // serde adapter module name. Without the codegen-time guard, this
        // would emit two `pub mod _severity_serde { ... }` blocks and
        // produce a confusing rustc error far from the .fbs file.
        let enums = vec![
            Enum {
                name: "Severity".to_string(),
                variants: vec!["Info".to_string()],
            },
            Enum {
                name: "severity".to_string(),
                variants: vec!["Info".to_string()],
            },
        ];
        let mut output = String::new();
        generate_plain_struct_module(&mut output, "v_1", &[], &enums);
    }

    #[test]
    fn test_generate_flatbed_module_with_enum_field() {
        let mut schemas = HashMap::new();
        schemas.insert(
            "v_1".to_string(),
            vec![Table {
                name: "BoxPortInfo".to_string(),
                fields: vec![
                    Field {
                        name: "name".to_string(),
                        fbs_type: "string".to_string(),
                        default: None,
                    },
                    Field {
                        name: "port".to_string(),
                        fbs_type: "uint16".to_string(),
                        default: None,
                    },
                    Field {
                        name: "protocol".to_string(),
                        fbs_type: "BoxProtocol".to_string(),
                        default: None,
                    },
                ],
            }],
        );
        let mut enums = HashMap::new();
        enums.insert(
            "v_1".to_string(),
            vec![Enum {
                name: "BoxProtocol".to_string(),
                variants: vec![
                    "HTTP1".to_string(),
                    "HTTP2".to_string(),
                    "TCP".to_string(),
                    "GRPC".to_string(),
                ],
            }],
        );
        let module = generate_flatbed_module(&schemas, &enums, "test");

        // Enum is re-exported into the namespace so callers can write
        // `generated::v_1::BoxProtocol::HTTP1` without crossing `__fb`.
        assert!(module.contains("pub use super::__fb::v_1::BoxProtocol;"));
        // Per-enum serde adapter module — needed because the flatc enum
        // doesn't derive Serialize/Deserialize and we can't impl them
        // ourselves under the orphan rule.
        assert!(module.contains("pub mod _boxprotocol_serde {"));
        assert!(module.contains("pub mod _boxprotocol_opt_vec_serde {"));
        // Bare-enum struct field — no Option wrapper.
        assert!(module.contains("pub protocol: BoxProtocol,"));
        // utoipa schema override — the flatc enum doesn't implement
        // `ComposeSchema`, so we tell `ToSchema` the JSON form is a String.
        // The serde adapter below makes that declaration honest.
        assert!(module.contains("#[schema(value_type = String)]"));
        // serde adapter wired onto the field via `#[serde(with = ...)]`,
        // with `default` so JSON callers that omit the key get the zero
        // variant (matches FB "absent scalar = first variant" semantics).
        assert!(module.contains("#[serde(with = \"_boxprotocol_serde\", default)]"));
        // Adapter round-trips JSON as variant-name strings, not the
        // underlying integer. Both directions are present:
        //   serialize: maps variants to their declared names
        //   deserialize: matches a string against each variant name
        // Each variant must appear in both branches.
        assert!(module.contains("if *v == BoxProtocol::HTTP1 { \"HTTP1\" }"));
        assert!(module.contains("else if *v == BoxProtocol::GRPC { \"GRPC\" }"));
        assert!(module.contains("\"HTTP1\" => Ok(BoxProtocol::HTTP1)"));
        assert!(module.contains("\"GRPC\" => Ok(BoxProtocol::GRPC)"));
        // VALID_NAMES is built from the parsed variant list — both for
        // unknown-variant errors and for the OpenAPI-shaped contract.
        assert!(module
            .contains("const VALID_NAMES: &[&str] = &[\"HTTP1\", \"HTTP2\", \"TCP\", \"GRPC\"];"));
        // Encoder: scalar-style emission (no `_offset` indirection).
        assert!(module.contains("protocol: self.protocol,"));
        // Decoder: scalar-style accessor (no `.map(...)`).
        assert!(module.contains("protocol: fb.protocol(),"));
    }

    #[test]
    fn test_generate_flatbed_module_with_field_default_emits_custom_default_impl() {
        // A table with any FB-declared non-zero default drops `Default`
        // from the derive list (per-field hand-written impl follows) and
        // emits an `impl Default for X` block whose fields use the
        // declared literal where set and fall back to
        // `Default::default()` otherwise. Tables that share the
        // namespace but have no defaults keep `#[derive(Default)]`.
        let mut schemas = HashMap::new();
        schemas.insert(
            "v_1".to_string(),
            vec![
                Table {
                    name: "Defaulted".to_string(),
                    fields: vec![
                        Field {
                            name: "port".to_string(),
                            fbs_type: "uint16".to_string(),
                            default: Some("8080".to_string()),
                        },
                        Field {
                            name: "retries".to_string(),
                            fbs_type: "int32".to_string(),
                            default: None,
                        },
                    ],
                },
                Table {
                    name: "Plain".to_string(),
                    fields: vec![Field {
                        name: "value".to_string(),
                        fbs_type: "uint16".to_string(),
                        default: None,
                    }],
                },
            ],
        );
        let enums: HashMap<String, Vec<Enum>> = HashMap::new();
        let module = generate_flatbed_module(&schemas, &enums, "test");

        // Defaulted: derive drops `Default`, custom impl emitted, port
        // gets the literal, retries falls back to `Default::default()`.
        assert!(module
            .contains("#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, ToSchema)]\n"));
        assert!(module.contains("impl Default for Defaulted {"));
        assert!(module.contains("port: 8080,"));
        assert!(module.contains("retries: Default::default(),"));

        // Plain: derive keeps `Default`, no custom impl emitted. Pin
        // both — a regression where the conditional fired uniformly
        // would silently rewrite every committed snapshot.
        assert!(module.contains(
            "#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq, ToSchema)]\n"
        ));
        assert!(!module.contains("impl Default for Plain"));
    }

    #[test]
    fn test_generate_flatbed_module_with_enum_vector_field() {
        let mut schemas = HashMap::new();
        schemas.insert(
            "v_1".to_string(),
            vec![Table {
                name: "LogEvent".to_string(),
                fields: vec![Field {
                    name: "history".to_string(),
                    fbs_type: "[Severity]".to_string(),
                    default: None,
                }],
            }],
        );
        let mut enums = HashMap::new();
        enums.insert(
            "v_1".to_string(),
            vec![Enum {
                name: "Severity".to_string(),
                variants: vec![
                    "Info".to_string(),
                    "Warning".to_string(),
                    "Error".to_string(),
                ],
            }],
        );
        let module = generate_flatbed_module(&schemas, &enums, "test");

        // `[Severity]` surfaces as `Option<Vec<Severity>>`.
        assert!(module.contains("pub history: Option<Vec<Severity>>"));
        // utoipa schema override on the vector field.
        assert!(module.contains("#[schema(value_type = Vec<String>)]"));
        // serde adapter on the vector field — uses the
        // `_<enum>_opt_vec_serde` module so JSON round-trips as a list of
        // variant-name strings (matches the schema declaration).
        assert!(module.contains("#[serde(with = \"_severity_opt_vec_serde\""));
        // The vector adapter shares the per-variant lookup table with the
        // bare-enum adapter; both reference the same VALID_NAMES list.
        assert!(
            module.contains("const VALID_NAMES: &[&str] = &[\"Info\", \"Warning\", \"Error\"];")
        );
        // Enum vectors take the scalar-vector encode path because flatc-emitted
        // enums implement `Push` + `Copy` and `create_vector` accepts them
        // directly without the per-element `build_flatbuffer` indirection used
        // for tables.
        assert!(module.contains("builder.create_vector(v)"));
        assert!(module.contains("v.iter().collect()"));
    }
}
