//! Generate `client.ts`: a zero-dependency `fetch` client that calls each
//! FlatBuffer operation of a flatbed service.
//!
//! Each method encodes the typed request with the generated codec, sends it as
//! `application/x-flatbuffers` using the operation's HTTP method, and decodes
//! the response the same way. Path parameters (`/users/{id}`) become leading
//! string arguments.

use crate::fb_plugin::FbOperation;

const CONTENT_TYPE: &str = "application/x-flatbuffers";

/// Generate `client.ts` for the FlatBuffer operations discovered in the spec.
pub(crate) fn generate(ops: &[FbOperation]) -> String {
    let mut imports_types: Vec<&str> = Vec::new();
    for op in ops {
        imports_types.extend(op.request_type.as_deref());
        imports_types.extend(op.response_type.as_deref());
    }
    imports_types.sort_unstable();
    imports_types.dedup();

    let mut out = String::from("// Auto-generated by flatbed — do not edit.\n\n");
    out.push_str("import * as codec from \"./codec.js\";\n");
    if !imports_types.is_empty() {
        out.push_str(&format!(
            "import type {{ {} }} from \"./types.js\";\n",
            imports_types.join(", ")
        ));
    }
    out.push('\n');
    out.push_str(&format!("const CONTENT_TYPE = \"{CONTENT_TYPE}\";\n\n"));
    out.push_str(PREAMBLE);

    out.push_str("export class FlatbedClient {\n");
    out.push_str("  constructor(private readonly options: ClientOptions) {}\n\n");
    for op in ops {
        out.push_str(&method(op));
    }
    out.push_str(REQUEST_METHOD);
    out.push_str("}\n");
    out
}

fn method(op: &FbOperation) -> String {
    let name = method_name(op);
    let params = path_params(&op.path);

    let mut args: Vec<String> = params.iter().map(|p| format!("{p}: string")).collect();
    let (body_expr, ret_type) = match (&op.request_type, &op.response_type) {
        (Some(req), _) => {
            args.push(format!("body: {req}"));
            (format!("codec.encode{req}Root(body)"), response_type(op))
        }
        (None, _) => ("new Uint8Array()".to_string(), response_type(op)),
    };
    let decode = match &op.response_type {
        Some(res) => format!("codec.decode{res}Root"),
        // No generated response type — hand back the raw bytes.
        None => "(bytes: Uint8Array) => bytes".to_string(),
    };

    let path_expr = if params.is_empty() {
        format!("\"{}\"", op.path)
    } else {
        let mut tmpl = op.path.clone();
        for p in &params {
            tmpl = tmpl.replace(&format!("{{{p}}}"), &format!("${{{p}}}"));
        }
        format!("`{tmpl}`")
    };

    format!(
        "  async {name}({args}): Promise<{ret_type}> {{\n\
         \x20   return this.request(\"{method}\", {path_expr}, {body_expr}, {decode});\n\
         \x20 }}\n\n",
        args = args.join(", "),
        method = op.method,
    )
}

/// `operationId` when present, else `<method><PascalPathSegments>` — e.g.
/// `GET /users/{id}` → `getUsersById`.
fn method_name(op: &FbOperation) -> String {
    if let Some(id) = &op.operation_id {
        return camel_case(id);
    }
    let mut name = op.method.to_lowercase();
    for seg in op.path.split('/').filter(|s| !s.is_empty()) {
        let seg = seg.trim_start_matches('{').trim_end_matches('}');
        let param = op.path.contains(&format!("{{{seg}}}"));
        let word = if param {
            format!("By{}", pascal(seg))
        } else {
            pascal(seg)
        };
        name.push_str(&word);
    }
    name
}

fn response_type(op: &FbOperation) -> String {
    match &op.response_type {
        Some(res) => res.clone(),
        None => "Uint8Array".to_string(),
    }
}

/// The `{param}` names in a path, in order.
fn path_params(path: &str) -> Vec<String> {
    path.split('/')
        .filter_map(|seg| {
            seg.strip_prefix('{')
                .and_then(|s| s.strip_suffix('}'))
                .map(str::to_string)
        })
        .collect()
}

/// Turn an `operationId` into a camelCase method name: `GetUser`, `get_user`
/// and `get-user` all become `getUser`.
fn camel_case(s: &str) -> String {
    let mut out = String::new();
    let mut first = true;
    let mut capitalize_next = false;
    for c in s.chars() {
        if !c.is_alphanumeric() {
            capitalize_next = !first;
        } else if first {
            out.extend(c.to_lowercase());
            first = false;
        } else if capitalize_next {
            out.extend(c.to_uppercase());
            capitalize_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn pascal(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => s.to_string(),
    }
}

const PREAMBLE: &str = "\
export interface ClientOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
}

export class FlatbedError extends Error {
  constructor(readonly status: number, message: string) {
    super(message);
    this.name = \"FlatbedError\";
  }
}

";

const REQUEST_METHOD: &str = "  private async request<T>(
    method: string,
    path: string,
    body: Uint8Array,
    decode: (bytes: Uint8Array) => T,
  ): Promise<T> {
    const fetchImpl = this.options.fetch ?? globalThis.fetch;
    const init: RequestInit = { method, headers: { accept: CONTENT_TYPE } };
    // A bodyless operation (GET/HEAD) must not set a body — browser `fetch`
    // rejects it. `body as BodyInit` casts past the generic-`Uint8Array` friction.
    if (body.length > 0) {
      (init.headers as Record<string, string>)[\"content-type\"] = CONTENT_TYPE;
      init.body = body as BodyInit;
    }
    const res = await fetchImpl(this.options.baseUrl + path, init);
    if (!res.ok) {
      throw new FlatbedError(res.status, `${method} ${path} failed: ${res.status}`);
    }
    return decode(new Uint8Array(await res.arrayBuffer()));
  }
";

#[cfg(test)]
mod tests {
    use super::*;

    fn op(method: &str, path: &str, req: Option<&str>, res: Option<&str>) -> FbOperation {
        FbOperation {
            path: path.to_string(),
            method: method.to_string(),
            operation_id: None,
            request_type: req.map(str::to_string),
            response_type: res.map(str::to_string),
        }
    }

    #[test]
    fn method_encodes_request_and_decodes_response() {
        let client = generate(&[op(
            "POST",
            "/echo",
            Some("EchoRequest"),
            Some("EchoResponse"),
        )]);
        assert!(client.contains("import type { EchoRequest, EchoResponse } from \"./types.js\";"));
        assert!(client.contains("async postEcho(body: EchoRequest): Promise<EchoResponse> {"));
        assert!(client.contains(
            "return this.request(\"POST\", \"/echo\", codec.encodeEchoRequestRoot(body), codec.decodeEchoResponseRoot);"
        ));
    }

    #[test]
    fn path_params_become_leading_string_args() {
        let client = generate(&[op("GET", "/users/{id}", Some("Empty"), Some("User"))]);
        assert!(client.contains("async getUsersById(id: string, body: Empty): Promise<User> {"));
        assert!(client.contains("return this.request(\"GET\", `/users/${id}`,"));
    }

    #[test]
    fn operation_id_wins_over_derived_name() {
        let mut o = op("POST", "/echo", Some("EchoRequest"), Some("EchoResponse"));
        o.operation_id = Some("EchoMessage".to_string());
        let client = generate(&[o]);
        assert!(client.contains("async echoMessage("));
    }

    #[test]
    fn missing_response_type_returns_raw_bytes() {
        let client = generate(&[op("POST", "/raw", Some("Req"), None)]);
        assert!(client.contains("Promise<Uint8Array>"));
        assert!(client.contains("(bytes: Uint8Array) => bytes"));
    }

    #[test]
    fn bodyless_get_sends_no_body() {
        let client = generate(&[op("GET", "/health", None, Some("Health"))]);
        assert!(client.contains("async getHealth(): Promise<Health> {"));
        // the request helper only attaches a body/content-type when non-empty,
        // so a GET (empty body) doesn't trip browser fetch's no-body rule
        assert!(client.contains("if (body.length > 0) {"));
    }

    #[test]
    fn snake_case_operation_id_becomes_camel() {
        let mut o = op("POST", "/x", Some("Req"), Some("Res"));
        o.operation_id = Some("create_user".to_string());
        let client = generate(&[o]);
        assert!(client.contains("async createUser("));
    }
}
